<div class="content-wrapper">
	<div class="page-title">
		<div class="row">
			<div class="col-sm-6">
				<h4 class="mb-0"> Change Password</h4>
			</div>
			<div class="col-sm-6">
				<ol class="breadcrumb pt-0 pr-0 float-left float-sm-right">
					<li class="breadcrumb-item"><a href="#" class="default-color">Home</a></li>
					<li class="breadcrumb-item active">Change Password</li>
				</ol>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-xl-6 mb-30">
			<div class="card card-statistics mb-30">
				<div class="card-body">
					<h5 class="card-title">Change Password</h5>
					<form method="post" id="changePasswordForm" class="ui grid form" novalidate="novalidate">
						<div class="row field">
							<label class="twelve wide column" for="password">Old Password</label>
							<div class="twelve wide column">
								<div class="ui input">
									<input id="password" name="password" type="text" placeholder="Old Password">
								</div>
							</div>
						</div>
						<div class="row field">
							<label class="twelve wide column" for="password1">New Password</label>
							<div class="twelve wide column">
								<div class="ui input">
									<input id="password1" name="password1" type="text" placeholder="New Password">
								</div>
							</div>
						</div>
						<div class="row field">
							<label class="twelve wide column" for="password2">Retype New Password</label>
							<div class="twelve wide column">
								<div class="ui input">
									<input id="password2" name="password2" type="text" placeholder="Retype New Password">
								</div>
							</div>
						</div>
						<div class="row">
							<label class="twelve wide column"></label>
							<div class="twelve wide column">
								<button type="submit" class="btn btn-primary ml-15">Change Password</button>
							</div>
						</div>
						<input type="hidden" name="change_password" value="1">
					</form>
				</div>
			</div>
		</div>
	</div>