
		<div id="header">
			<div class="color-line">
			</div>
			<div id="logo" style="text-align:center;" class="light-version">
				<span>
					MOSGRUP
				</span>
			</div>
			<nav role="navigation">
				<div class="header-link hide-menu"><i class="fa fa-bars"></i></div>
				<div class="small-logo">
					<span class="text-primary">MOSGRUP</span>
				</div>
				<div class="mobile-menu">
					<button type="button" class="navbar-toggle mobile-menu-toggle" style="font-size: 18px;"
						data-toggle="collapse" data-target="#mobile-collapse" aria-expanded="true">
						<i class="fas fa-user-cog"></i>
					</button>
					<div class="mobile-navbar collapse" id="mobile-collapse" aria-expanded="true" style>
						<div style="padding: 0;margin: 0;border-bottom: 1px solid #eaeaea;">
							<!-- <div class="right_block_body"> -->
							<!-- <div class="row">
    <div class="col-lg-12"> -->
							{user_reg}
							<!-- </div>
								</div> -->
							<!-- </div> -->
						</div>
					</div>
				</div>
				<!-- Навигационное меню -->
				<div class="navbar-right">
					<ul id="menu-verxnee-menyu" class="nav navbar-nav no-borders">
						<li id="menu-item-31" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-31">
							<a title="FAQ" href="./?p=faq">FAQ</a></li>
						<li id="menu-item-67" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-67">
						<a title="Контакты" href="./?p=contact">Контакты</a></li>
					</ul>
					<ul class="nav navbar-nav no-borders">
						<li class="dropdown">
							<a rel="nofollow" class="opensiduser" href="#"
								style=" font-size: 20px; color: #ffffff; background: #1ec752; border-bottom: 1px solid #e4e5e7;">
								<i class="fas fa-user-cog"></i>
							</a>
						</li>
					</ul>
				</div>
			</nav>
		</div>


		<!--Левая сторона-->

		<aside id="menu">
		<!--Левая навигация -->
		<div id="navigation">
			<div style="padding: 10px;" class="profile-picture">
				<a href="/">
					<img src="images/ZT0MS3qaVzI2.png" class alt="GlazOk.org">
				</a>
				<div class="stats-label text-color">
					<span class="font-extra-bold font-uppercase">Общий чат Химиков!</span>
					<div>
						<small class="text-muted" style="line-height:1">
							<div class="rightblock">Все преимущества напрямую заключать сделки с производителями.</div>
						</small>
					</div>
				</div>
			</div>
	
			


		


			<ul id="side-menu" class="nav">
					<li id="menu-item-69" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-69">
					</li>

				{l_c_p}{left_control_shop} 
						<li id="menu-item-31" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-31">
							<a title="FAQ" href="./?p=faq">FAQ</a></li>
						<li id="menu-item-67" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-67">
						<a title="Контакты" href="./?p=contact">Контакты</a></li>
						
				</ul>


			<!--<ul id="side-menu" class="nav">
				<li id="menu-item-69" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-69">
					<a title="Добавить обменник" href="/dobavit-obmennik/">Добавить магазин</a></li>
			</ul>-->
		</div>
		
		<div class="row topcur" style="font-size: 11px;">
			<div class="col-md-12" style>
				<div class="hpanel">
					<div class="panel-body">
						<div class="stats-title">
							<h4>Bitcoin</h4>
						</div>
						<div class="stats-icon pull-right">
							<i class="fa fa-bitcoin text-warning" style="font-size: 2em;"></i>
						</div>
						<div class="m-t-none">
							<div class="h3">$<span class="value" id="currency-moved-value-BTCUSD2"></span> <span
									class="pos"></span></div>
							<small>
								Долларов за биткоин
							</small>
						</div>
						<div class="stats-title">
							<h4>Биткойн</h4>
						</div>
						<div class="stats-icon pull-right">
							<i class="fab fa-ethereum text-warning" style="font-size: 2em;"></i>
						</div>
						<div class="m-t-none">
							<div class="h3">$<span class="value" id="currency-moved-value-ETH"></span> <span
									class="pos"></span></div>
							<small>
								Биткойн за Продукт
							</small>
						</div>
					</div>
				</div>
			</div>
		</div>
	</aside>
	<div id="wrapper">
	<div class="content animates-panel">
	<div class="marquee"><span>Внимание! сервис запущен в тестовом режиме!</span></div>
