<div class="hpanel">
	<div class="row">  
		<div class="col-lg-8">
			<div class="panel-body" style="box-shadow: rgba(0, 0, 0, 0.26) 0px 0px 12px 1px;">  
				<div class="post-list table-responsive" id="post-list16">
					<div class="profileform" style="padding: 10px 0 20px; width: 300px;">
						<form action="./?p=profile" method="post">
							<table cellspacing="0" cellpadding="0" width="100%">
								<tbody><tr>
									<td>
										Логин:
									</td>	
									<td>
										{user_name}
									</td>
								</tr>		
								<tr>
									<td style="padding-top: 5px;">
										Ваше имя:
									</td>	
									<td>
										<input type="text" name="d_name" value="" autocomplete="off" class="newstyle" style="margin: 5px 0 0 0;" size="16">
									</td>
								</tr>			
								<tr>
									<td style="padding-top: 5px;">
										Новый пароль:
									</td>	
									<td>
										<input type="password" name="pass" value="" autocomplete="off" class="newstyle" style="margin: 5px 0 0 0;" size="16">
									</td>
								</tr>
								<tr>
									<td style="padding-top: 5px;">
										Новый пароль повторно:
									</td>	
									<td>
										<input type="password" name="pass2" value="" autocomplete="off" class="newstyle" style="margin: 5px 0 0 0;" size="16">
									</td>
								</tr>			
								<tr>
									<td>&nbsp;</td>
									<td>
									<input type="submit" style="margin-top: 10px" class="exchangers_button_widg" value="Сохранить">
									<input type="hidden" name="save_ld" value="1">
									</td>
								</tr>
							</tbody></table>
						</form>
					</div>
				</div> 
			</div>
		</div>
		{rightblock}
	</div>
</div>