<div class="col-lg-4">
							<div class>
								<div class="rightblock">
									<div class="row">
										<div class="col-lg-12">
											<div class>
												<div class="panel-body">
													<h5>Ваша история активности</h5>
													<div>Магазины:</div>
													<div>Продукты:</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="rightblock">
									<div class="mobileselectRight" style>
<!-- Правый выбор города-->
										<div class="row">
											<div class="col-xs-6" style="padding: 0px 5px;"><select
													class="js-source-states" style="width: 100%">Выбор говрода
													<option
														data-synonym="Москва"
														value="1">Москва</option>
												</select></div>
											<div class="col-xs-6" style="padding: 0px 5px;"><select
													class="js-source-states2" style="width: 100%">Выбор продукта
												
													<option
														data-synonym="Продукт"
														value="301">Диоксан HCl 38% </option>
													
												</select></div>
										</div>
									</div>
								</div>
								<div class="rightblock">
									<div class=" ">
										<div class="tab-content">
											<div id="tableView1" class="tab-pane  active">
												<div style="display:none" class="panel-body">
													<table class="change_select_widget exchange table  table-bordered  no-footer no_background" id="listView">
														<tbody>
															<tr>
																<td>
																</td>
															</tr>
															<tr style="height:10px;"></tr>
															<tr>
																<td>
																</td>
															</tr>
															<tr>
																<td colspan="2" align="center">
																	<input type="button"
																		class="btn btn-primary exchangers_button_huge"
																		name="show" id="showCoursesButton"
																		onclick="mchange_widget()"
																		value="Найти лучший курс">
																</td>
															</tr>
														</tbody>
													</table>
												</div>
												<div class="panel-body">
													<table cellpadding="1" cellspacing="1"
														class="table table-bordered table-hover table-striped"
														id="tableView">
														<tbody>
															<tr class="titles">
																<td>
																	Город
																</td>
																<td class="right">
																	Продукт
																</td>
															</tr>
															<tr class="valutes_type" id="group_1">
																<td class="title-cell-tab" colspan="2">Города<div data-arrow="down"
																		class="arrow_updown fa fa-chevron-down"></div>
																</td>
															</tr>
															<tr class="group_1">
																<td class="not_padded"><a class="firstValute"
																	rel="RFBRUB" rel1="300" rel2
																	href="/obmen/RFBRUB-/"><img
																		src="images/a1J50ccS9tbx.png"> Москва</a></td>
															<td class="not_padded"><a class="changeValute"
																	rel="RFBRUB" rel1="92" rel2
																	href="/obmen/-RFBRUB/"><img
																		src="images/a1J50ccS9tbx.png"> Диоксан</a></td>
															</tr>
															<tr class="group_3">
																<td class="not_padded"><a class="firstValute"
																		rel="RFBRUB" rel1="92" rel2
																		href="/obmen/RFBRUB-/"><img
																			src="images/a1J50ccS9tbx.png"> Москва
																		</a></td>
																<td class="not_padded"><a class="changeValute"
																		rel="RFBRUB" rel1="92" rel2
																		href="/obmen/-RFBRUB/"><img
																			src="images/a1J50ccS9tbx.png"> Бензол</a></td>
															</tr>
														</tbody>
													</table>
													<div class="text-center">
														<button type="button" id="showcur" class="btn btn-success">
															показать все города и продукты
														</button>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>