<tr class="favoriteclass_{id}">
	<td style="text-align: center;"> <i class="fa fa-check-square text-success" data-toggle="tooltip" data-placement="top" title="Безопасен"></i>
	</td>
	<td width="36%" class="mx first_body linkGoo" data-stat="1" data-name="Favorite-exchanger" data-href="{link}">
		<i class="fa fa-lock " aria-hidden="true" data-toggle="tooltip" data-placement="top" title="Сайт работает по защищенному протоколу https"></i>
		<a target="top" rel="nofollow" data-stat="1" data-name="Favorite-exchanger" data-href="{link}">{shop_name}</a>
		<div><span style="font-size: 8px; color: red; display: inline-block;">мин {min}</span> / <span style="font-size: 8px; color: red; display: inline-block;">макс {max}</span></div>
	</td>
	<td width="23%" class="mx formatGive linkGoo" data-href="{link}">
		<span>{sity}</span>
	</td>
	<td width="23%" class="mx formatGet linkGoo " data-href="{link}">
		<strong>{product}</strong>
	</td>
	<td width="13%" align="right" class="mx linkGoo " data-href="{link}">
		<strong>{reserve}</strong>
	</td>
	<td width="9%" align="center" class="mx" style="cursor:pointer" onclick="window.open('/exchange/?details=163'); return false">
		<span data-toggle="tooltip" data-placement="top" title="0 отрицательных отзыва" aria-hidden="true" class="js_right"
			style="display:block; float:left; width: 30px; height: 10px; text-align:right; border-bottom-color: #990000; border-bottom-width: 0px; border-bottom-style: solid;">0
		</span>
		<span style="display:block; width:3px;height:10px; float:left;">/</span>
		<span data-toggle="tooltip" data-placement="top" title="0 положительных отзывов" aria-hidden="true" class="js_right"
			style="display:block; float:left; width: 10px; height: 10px; text-align:center; color: #008000; border-bottom-color: #990000; border-bottom-width: 0px; border-bottom-style: solid">0
		</span>
	</td>
</tr>