<div class="hpanel">
	<div class="row">
		<div class="col-lg-12">
			<div class="panel-body" style="box-shadow: rgba(0, 0, 0, 0.26) 0px 0px 12px 1px;">
				<div class="post-list table-responsive" id="post-list257">
				
				
				
				
					<h1>Регистрация в партнерской программе</h1>
					<p>Пожалуйста, внимательно и аккуратно заполните все поля регистрационной формы. <br>
					</p>
					<div class="registerform" style="padding: 10px 0 20px; width: 300px;">
						<form action="" method="post">
							<table cellspacing="0" cellpadding="0" width="100%">
								<tbody><tr>
									<td>
										Логин:
									</td>	
									<td>
										<input type="text" name="log" class="newstyle" value="" autocomplete="off" style="margin: 5px 0 0 0;" size="16">
									</td>
								</tr>
								<tr>
									<td style="padding-top: 5px;">
										Пароль:
									</td>	
									<td>
										<input type="password" name="pwd" class="newstyle" style="margin: 5px 0 0 0;" autocomplete="off" id="user_pass_r2" value="" size="16">
									</td>
								</tr>			
								<tr>
									<td style="padding-top: 5px;">
										Пароль повторно:
									</td>	
									<td>
										<input type="password" name="pwd2" class="newstyle" style="margin: 5px 0 0 0;" autocomplete="off" id="user_pass2_r2" value="" size="16">
									</td>
								</tr>
								<tr>
									<td style="padding-top: 5px;">
										<s id="captcha_up"><img src="scripts/captaha.php?s=up&v=000" onclick="reload_up(); return false;" border="0" alt="Reload" style="height: 23px;cursor: wait;"/></s>
									</td>	
									<td>
										<input type="text" name="captaha_up" style="margin: 5px 0 0 0;" autocomplete="off" id="user_pass2_r2" value="" size="16">
									</td>
								</tr>
								<tr>
									<td>
									&nbsp;
									</td>
									<td>
									<p><input type="checkbox" name="check" style="margin: 5px 5px 0 0;" autocomplete="off" value="1" size="12"> Я принимаю <a href="#">условия</a></p>
									<input type="submit" class="exchangers_button_widg" value="Регистрация">
									<input type="hidden" name="sign_up" value="1">
									</td>
								</tr>		
							</tbody></table>
						</form>	
					</div>
					
					
					
					
				</div>
			</div>
		</div>
	</div>
</div>
<script language="JavaScript" type="text/javascript">
	function reload_up() {
		var rndval = new Date().getTime(); 
		$('#captcha_up').html('<img src="scripts/captaha.php?s=up&v='+rndval+'" onclick="reload_up(); return false;" border="0"  alt="Reload" style="height: 23px;cursor: wait;"/>');
	};
	clickButton = function(e) {
		var keynum;
		if(window.event) {
			keynum = e.keyCode;
		} else if(e.which) {
			keynum = e.which;
		}
		if(keynum == 13) $('a#sign_in').click();
	}
</script>
