<ul id="side-menu" class="nav">
					<li id="menu-item-69" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-69">
					</li>

						<li id="menu-item-31" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-31">
							<a title="FAQ" href="./?p=faq">FAQ</a></li>
						<li id="menu-item-67" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-67">
						<a title="Контакты" href="./?p=contact">Контакты</a></li>
				</ul>