<div class="hpanel">
						<div class="panel-heading hbuilt">
							Войти в личный кабинет </div>
						<div class="panel-body no-padding">
							<div style="padding: 0 0 0 30px;">
								<form action method="post">
									<table cellspacing="0" cellpadding="0" width="100%">
										<tbody>
											<tr>
												<td>
													Логин:
												</td>
												<td>
													<input type="text" name="log" value autocomplete="off"
														style="margin: 5px 0 0 0;" size="16" class="newstyle">
												</td>
											</tr>
											<tr>
												<td style="padding-top: 5px;">
													Пароль:
												</td>
												<td>
													<input type="password" name="pwd" style="margin: 5px 0 0 0;"
														autocomplete="off" value size="16" class="newstyle">
												</td>
											</tr>
											<tr>
												<td style="padding-top: 5px;width: 70px;">
													<s id="captcha_in"><img src="scripts/captaha.php?s=in&v=000" onclick="reload_in(); return false;" border="0" alt="Reload" style="height: 18px;cursor: wait;"/></s>
												</td>
												<td>
													<input type="text" name="captaha_in" style="margin: 5px 0 0 0;"
														autocomplete="off" value size="16" class="newstyle">
												</td>
											</tr>
											<tr>
												<td style="padding-top: 5px;">
													 
												</td>
												<td>
													<input type="submit" style="margin: 10px 0 0"
														class="exchangers_button_widg" value="Войти">
													<input type="hidden" name="sign_in" value="1">
												</td>
											</tr>
											<tr>
												<td colspan="2" class="info_left" style="padding: 10px 0 0;">
													<p><a
															href="./?p=sign_up" title="Регистрация">Регистрация</a></p>
												</td>
											</tr>
										</tbody>
									</table>
								</form>
							</div>
						</div>
					</div>